### PR TITLE
Updates A-S to latest main

### PR DESCRIPTION
**Pull request by tarikeshaq**

### CODE REVIEW

**Comment by tarikeshaq** [comment]
This should wait until https://github.com/mozilla/application-services/pull/4396 merges, then I'll update this PR to point to main (which will have the changes we want)

**Comment by skhamis** [comment]
#4396 was merged so once this is updated with latest `HEAD` we can merge this!

**Comment by tarikeshaq** [comment]
Updated this to point to the `main` after https://github.com/mozilla/application-services/pull/4396 was merged 😄 This should be ready to merge

**Review by skhamis — APPROVED** [review]
PR #1 wohoo! 🚀

**Pull request merged**
